# Generated by Django 3.2.13 on 2022-05-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipotreino',
            name='treinos',
        ),
        migrations.AddField(
            model_name='diasemana',
            name='treino',
            field=models.ManyToManyField(to='academia.TipoTreino'),
        ),
    ]
