# Generated by Django 3.2.13 on 2022-05-22 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_auto_20220522_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diasemana',
            name='descricao',
        ),
    ]
