# Generated by Django 3.2.13 on 2022-05-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_remove_diasemana_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tipotreino',
            name='exercicio',
            field=models.ManyToManyField(to='academia.Exercicio'),
        ),
    ]
