# Generated by Django 3.2.13 on 2022-05-22 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('academia', '0004_auto_20220522_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diasemana',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
